version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  build_and_push:
    executor: docker-executor
    steps:
      - checkout  # Checkout the code from the repository
      - setup_remote_docker:
          docker_layer_caching: true  # Enable Docker layer caching for faster builds

      # Log into Docker Hub
      - run:
          name: Log into Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build images with docker-compose
      - run:
          name: Build images using docker-compose
          command: |
            docker-compose -f docker-compose-build.yaml build

      # Tag images with commit hash (or Git tag)
      - run:
          name: Tag and Push reverseproxy image
          command: |
            IMAGE_TAG="$DOCKER_USERNAME/reverseproxy:${CIRCLE_SHA1}"  # Unique version tag
            docker tag reverseproxy "$IMAGE_TAG"
            docker push "$IMAGE_TAG"

      - run:
          name: Tag and Push udagram-api-user image
          command: |
            IMAGE_TAG="$DOCKER_USERNAME/udagram-api-user:${CIRCLE_SHA1}"  # Unique version tag
            docker tag udagram-api-user "$IMAGE_TAG"
            docker push "$IMAGE_TAG"

      - run:
          name: Tag and Push udagram-api-feed image
          command: |
            IMAGE_TAG="$DOCKER_USERNAME/udagram-api-feed:${CIRCLE_SHA1}"  # Unique version tag
            docker tag udagram-api-feed "$IMAGE_TAG"
            docker push "$IMAGE_TAG"

      - run:
          name: Tag and Push udagram-frontend image
          command: |
            IMAGE_TAG="$DOCKER_USERNAME/udagram-frontend:${CIRCLE_SHA1}"  # Unique version tag
            docker tag udagram-frontend:local "$IMAGE_TAG"
            docker push "$IMAGE_TAG"

      # Optionally, tag the latest version as 'latest' (for the most recent image)
      - run:
          name: Tag and Push 'latest' image
          command: |
            docker tag "$DOCKER_USERNAME/udagram-api-user:${CIRCLE_SHA1}" "$DOCKER_USERNAME/udagram-api-user:latest"
            docker push "$DOCKER_USERNAME/udagram-api-user:latest"
            docker tag "$DOCKER_USERNAME/udagram-api-feed:${CIRCLE_SHA1}" "$DOCKER_USERNAME/udagram-api-feed:latest"
            docker push "$DOCKER_USERNAME/udagram-api-feed:latest"
            docker tag "$DOCKER_USERNAME/udagram-frontend:${CIRCLE_SHA1}" "$DOCKER_USERNAME/udagram-frontend:latest"
            docker push "$DOCKER_USERNAME/udagram-frontend:latest"
            docker tag "$DOCKER_USERNAME/reverseproxy:${CIRCLE_SHA1}" "$DOCKER_USERNAME/reverseproxy:latest"
            docker push "$DOCKER_USERNAME/reverseproxy:latest"

workflows:
  version: 2
  build:
    jobs:
      - build_and_push