apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-feed-hpa
  namespace: default  # Change if your deployment is in another namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-feed
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 500Mi  # Set the desired average memory usage per pod

